project:
  type: website
  output-dir: docs

title: "RadExIORSBoost ML tutorial"

# Move the sidebar inside a website wrapper
website:
  sidebar:
    title: "Tutorials"
    style: "floating"
    background: light
    contents:
      - boost_ml.qmd

# Change html to live-html to match your document's target format
format:
  live-html: default
# Don't execute R code on GitHub
execute:
  freeze: auto